sourceBucket: ""
destBucket: ""
awsRoleARN: ""
env:
  AWS_REGION: ""
  AWS_ENVIRONMENT: production
  AWS_FUNCTION_NAME: image-optimizer
  AWS_HANDLER: index.optimize
  AWS_MEMORY_SIZE: 256
  AWS_TIMEOUT: 300
  AWS_RUNTIME: nodejs6.10
  UPLOAD_ACL: public-read
  PNG_OPTIM_LEVEL: 7
  GIF_OPTIM_INTERLACED: true
  JPG_OPTIM_PROGRESSIVE: true
  MAX_FILE_SIZE: -1
  # define it to avoid optimization on images having specific prefix
  EXCLUDE_PREFIX: "FBHRes-"

